# ECON 5105 Homework 1

# Part A. Conceptual / Manual Problems

1\. Basic Operations

$$
A=\begin{bmatrix}1&2\\3&4\end{bmatrix},\quad B=\begin{bmatrix}2&0\\1&2\end{bmatrix}
$$

(a) add / subtract the entries in the same position:

$$
A+B=\begin{bmatrix}1+2&2+0\\3+1&4+2\end{bmatrix}=\begin{bmatrix}3&2\\4&6\end{bmatrix}
$$

$$
A-B=\begin{bmatrix}1-2&2-0\\3-1&4-2\end{bmatrix}=\begin{bmatrix}-1&2\\2&2\end{bmatrix}
$$

(b) multiply every entry by 2:

$$
2A=\begin{bmatrix}2(1)&2(2)\\2(3)&2(4)\end{bmatrix}=\begin{bmatrix}2&4\\6&8\end{bmatrix}
$$

(c) each entry is a row of the first matrix times a column of the second:

$$
AB=\begin{bmatrix}1(2)+2(1)&1(0)+2(2)\\3(2)+4(1)&3(0)+4(2)\end{bmatrix}=\begin{bmatrix}4&4\\10&8\end{bmatrix}
$$

$$
BA=\begin{bmatrix}2(1)+0(3)&2(2)+0(4)\\1(1)+2(3)&1(2)+2(4)\end{bmatrix}=\begin{bmatrix}2&4\\7&10\end{bmatrix}
$$

AB is not equal to BA. Matrix multiplication is not commutative. In AB we multiply the rows of A by the columns of B, but in BA it is the rows of B times the columns of A, so different numbers get multiplied together. For example the top left entry is 1(2)+2(1) = 4 in AB but 2(1)+0(3) = 2 in BA.

2\. Properties of Special Matrices

1\) diagonal matrix (everything off the main diagonal is 0):

$$
\begin{bmatrix}3&0&0\\0&-1&0\\0&0&5\end{bmatrix}
$$

2\) identity matrix (1s on the diagonal, 0s everywhere else):

$$
I_3=\begin{bmatrix}1&0&0\\0&1&0\\0&0&1\end{bmatrix}
$$

3\) symmetric matrix ($S^T=S$):

$$
S=\begin{bmatrix}1&4&5\\4&2&6\\5&6&3\end{bmatrix},\quad S^T=\begin{bmatrix}1&4&5\\4&2&6\\5&6&3\end{bmatrix}=S
$$

4\) idempotent matrix ($M^2=M$):

$$
M=\begin{bmatrix}3&-6\\1&-2\end{bmatrix}
$$

$$
M^2=\begin{bmatrix}3(3)+(-6)(1)&3(-6)+(-6)(-2)\\1(3)+(-2)(1)&1(-6)+(-2)(-2)\end{bmatrix}=\begin{bmatrix}9-6&-18+12\\3-2&-6+4\end{bmatrix}=\begin{bmatrix}3&-6\\1&-2\end{bmatrix}=M
$$

3\. Systems of Equations

2x + y = 5, 3x - y = 4

matrix form Ax = b:

$$
\begin{bmatrix}2&1\\3&-1\end{bmatrix}\begin{bmatrix}x\\y\end{bmatrix}=\begin{bmatrix}5\\4\end{bmatrix}
$$

determinant:

$$
|A|=a_{22}a_{11}-a_{21}a_{12}=(-1)(2)-(3)(1)=-2-3=-5
$$

$|A|\neq0$ so A is invertible.

inverse:

$$
A^{-1}=\frac{1}{a_{22}a_{11}-a_{21}a_{12}}\begin{bmatrix}a_{22}&-a_{12}\\-a_{21}&a_{11}\end{bmatrix}=\frac{1}{-5}\begin{bmatrix}-1&-1\\-3&2\end{bmatrix}=\begin{bmatrix}1/5&1/5\\3/5&-2/5\end{bmatrix}
$$

check:

$$
AA^{-1}=\begin{bmatrix}2(1/5)+1(3/5)&2(1/5)+1(-2/5)\\3(1/5)+(-1)(3/5)&3(1/5)+(-1)(-2/5)\end{bmatrix}=\begin{bmatrix}1&0\\0&1\end{bmatrix}
$$

solve:

$$
\begin{bmatrix}x\\y\end{bmatrix}=A^{-1}b=\begin{bmatrix}1/5&1/5\\3/5&-2/5\end{bmatrix}\begin{bmatrix}5\\4\end{bmatrix}
$$

$$
=\begin{bmatrix}(1/5)(5)+(1/5)(4)\\(3/5)(5)+(-2/5)(4)\end{bmatrix}=\begin{bmatrix}1+4/5\\3-8/5\end{bmatrix}=\begin{bmatrix}9/5\\7/5\end{bmatrix}
$$

x = 9/5 = 1.8, y = 7/5 = 1.4

check: 2(1.8) + 1.4 = 5, 3(1.8) - 1.4 = 4

4\. Determinant & Rank

$$
C=\begin{bmatrix}1&2&3\\1&1&1\\3&5&7\end{bmatrix}
$$

(a) cofactor expansion along row 1:

$$
|C|=1\begin{vmatrix}1&1\\5&7\end{vmatrix}-2\begin{vmatrix}1&1\\3&7\end{vmatrix}+3\begin{vmatrix}1&1\\3&5\end{vmatrix}
$$

$$
=1(7-5)-2(7-3)+3(5-3)=1(2)-2(4)+3(2)=2-8+6=0
$$

so $|C|=0$ (row 3 = 2 × row 1 + row 2, that's why it comes out to 0)

(b) row reduce:

R2 - R1: (1-1, 1-2, 1-3) = (0, -1, -2)

R3 - 3R1: (3-3, 5-6, 7-9) = (0, -1, -2)

$$
\begin{bmatrix}1&2&3\\0&-1&-2\\0&-1&-2\end{bmatrix}
$$

R3 - R2: (0-0, -1-(-1), -2-(-2)) = (0, 0, 0)

$$
\begin{bmatrix}1&2&3\\0&-1&-2\\0&0&0\end{bmatrix}
$$

2 nonzero rows (2 pivots), so rank(C) = 2.

(c) The rank is 2 but C is 3×3, so only 2 of the 3 rows are linearly independent. Row 3 is just 2 × row 1 + row 2, so it doesn't add any new information. That means C is not full rank: $|C|=0$, C is singular and has no inverse, and a system Cx = b can't have a unique solution (it has either no solution or infinitely many). If C were a data matrix in a regression, this would be perfect multicollinearity.

5\. Find the inverse of D

$$
D=\begin{bmatrix}2&1&0\\1&1&1\\0&1&1\end{bmatrix}
$$

Step 1: minors (delete row i and column j, then take the 2x2 determinant)

$$
M_{11}=\begin{vmatrix}1&1\\1&1\end{vmatrix}=1-1=0,\quad M_{12}=\begin{vmatrix}1&1\\0&1\end{vmatrix}=1-0=1,\quad M_{13}=\begin{vmatrix}1&1\\0&1\end{vmatrix}=1-0=1
$$

$$
M_{21}=\begin{vmatrix}1&0\\1&1\end{vmatrix}=1-0=1,\quad M_{22}=\begin{vmatrix}2&0\\0&1\end{vmatrix}=2-0=2,\quad M_{23}=\begin{vmatrix}2&1\\0&1\end{vmatrix}=2-0=2
$$

$$
M_{31}=\begin{vmatrix}1&0\\1&1\end{vmatrix}=1-0=1,\quad M_{32}=\begin{vmatrix}2&0\\1&1\end{vmatrix}=2-0=2,\quad M_{33}=\begin{vmatrix}2&1\\1&1\end{vmatrix}=2-1=1
$$

Step 2: cofactors $C_{ij}=(-1)^{i+j}M_{ij}$

$$
\begin{bmatrix}M_{11}&-M_{12}&M_{13}\\-M_{21}&M_{22}&-M_{23}\\M_{31}&-M_{32}&M_{33}\end{bmatrix}=\begin{bmatrix}0&-1&1\\-1&2&-2\\1&-2&1\end{bmatrix}
$$

Step 3: determinant, expand along row 1

$$
|D|=2(0)+1(-1)+0(1)=-1
$$

Step 4: adjoint = transpose of the cofactor matrix (same matrix here since it's symmetric)

$$
\text{adj}(D)=\begin{bmatrix}0&-1&1\\-1&2&-2\\1&-2&1\end{bmatrix}
$$

Step 5: inverse

$$
D^{-1}=\frac{1}{|D|}\text{adj}(D)=\frac{1}{-1}\begin{bmatrix}0&-1&1\\-1&2&-2\\1&-2&1\end{bmatrix}=\begin{bmatrix}0&1&-1\\1&-2&2\\-1&2&-1\end{bmatrix}
$$

check:

$$
DD^{-1}=\begin{bmatrix}2&1&0\\1&1&1\\0&1&1\end{bmatrix}\begin{bmatrix}0&1&-1\\1&-2&2\\-1&2&-1\end{bmatrix}=\begin{bmatrix}1&0&0\\0&1&0\\0&0&1\end{bmatrix}=I
$$

# Part B. Python Practice

Checking my answers from Part A with numpy.

In [1]:
import numpy as np

In [2]:
# Question 1
A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 0], [1, 2]])

print("A + B =\n", A + B)
print("A - B =\n", A - B)
print("2A =\n", 2 * A)

AB = A @ B
BA = B @ A
print("AB =\n", AB)
print("BA =\n", BA)
print("AB == BA ?", np.array_equal(AB, BA))

A + B =
 [[3 2]
 [4 6]]
A - B =
 [[-1  2]
 [ 2  2]]
2A =
 [[2 4]
 [6 8]]
AB =
 [[ 4  4]
 [10  8]]
BA =
 [[ 2  4]
 [ 7 10]]
AB == BA ? False


In [3]:
# Question 3
A = np.array([[2, 1], [3, -1]])
b = np.array([5, 4])

print("det(A) =", round(np.linalg.det(A), 4))

A_inv = np.linalg.inv(A)
print("A inverse =\n", A_inv)

x = A_inv @ b
print("x, y =", x)

det(A) = -5.0
A inverse =
 [[ 0.2  0.2]
 [ 0.6 -0.4]]
x, y = [1.8 1.4]


In [4]:
# Question 4 (a), (b)
C = np.array([[1, 2, 3], [1, 1, 1], [3, 5, 7]])

print("det(C) =", np.linalg.det(C))
print("rank(C) =", np.linalg.matrix_rank(C))

det(C) = -6.66133814775094e-16
rank(C) = 2


det(C) prints a very small number instead of exactly 0, that's just floating point error, so $|C|=0$. rank is 2, same as part A.

In [5]:
# Question 5
D = np.array([[2, 1, 0], [1, 1, 1], [0, 1, 1]])

print("det(D) =", round(np.linalg.det(D), 4))

D_inv = np.linalg.inv(D)
print("D inverse =\n", D_inv)
print("D @ D_inv =\n", D @ D_inv)

det(D) = -1.0
D inverse =
 [[ 0.  1. -1.]
 [ 1. -2.  2.]
 [-1.  2. -1.]]
D @ D_inv =
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


All the Python results match what I got by hand in Part A.